import os
import django
import sys

sys.path.append('c:/Users/xico0/Desktop/FantasyWorld_ScreamingArch')
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'src.Infrastructure.DjangoFramework.config.settings')
django.setup()

from src.WorldManagement.Caos.Infrastructure.django_repository import DjangoCaosRepository
from src.WorldManagement.Caos.Application.create_narrative import CreateNarrativeUseCase
from src.Infrastructure.DjangoFramework.persistence.models import CaosWorldORM, User

def test_creation():
    print("=== TESTING CREATION USE CASE ===")
    
    # Get a user and world
    u = User.objects.first()
    w = CaosWorldORM.objects.first()
    
    if not u or not w:
        print("CRITICAL: No user or world found to test.")
        return

    print(f"User: {u.username}")
    print(f"World: {w.name} (ID: {w.id})")
    
    repo = DjangoCaosRepository()
    use_case = CreateNarrativeUseCase(repo)
    
    try:
        print("Attempting to create generic LORE...")
        new_nid = use_case.execute(
            world_id=w.id,
            tipo_codigo='LORE',
            user=u,
            title="TEST_SCRIPT_CREATION",
            content="Debug content generated by script."
        )
        print(f"SUCCESS: Created Narrative {new_nid}")
        
    except Exception as e:
        print(f"CRITICAL FAILURE in CreateNarrativeUseCase: {e}")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    test_creation()
