# Generated by Django 5.0.1 on 2025-11-26 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaosEpochORM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('start_year', models.IntegerField(default=0)),
                ('end_year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'caos_epochs',
                'ordering': ['start_year'],
            },
        ),
        migrations.CreateModel(
            name='CaosWorldORM',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('id_codificado', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('id_lore', models.CharField(blank=True, max_length=40, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='DRAFT', max_length=50)),
                ('visible_publico', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_version_number', models.IntegerField(default=1)),
                ('current_author_name', models.CharField(blank=True, default='Sistema', max_length=150)),
                ('born_in_epoch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities_born', to='persistence.caosepochorm')),
                ('died_in_epoch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities_died', to='persistence.caosepochorm')),
            ],
            options={
                'db_table': 'caos_worlds',
            },
        ),
        migrations.CreateModel(
            name='CaosVersionORM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_name', models.CharField(max_length=150)),
                ('proposed_description', models.TextField(blank=True, null=True)),
                ('version_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='PENDING', max_length=30)),
                ('change_log', models.CharField(blank=True, max_length=255)),
                ('cambios', models.JSONField(blank=True, default=dict)),
                ('es_version_activa', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='persistence.caosworldorm')),
            ],
            options={
                'db_table': 'caos_versions',
                'ordering': ['-version_number'],
            },
        ),
    ]
