# Generated by Django 5.0.1 on 2025-11-28 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaosNarrativeORM',
            fields=[
                ('nid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('narrador', models.CharField(default='???', help_text='Entidad que relata el evento', max_length=150)),
                ('tipo', models.CharField(choices=[('LORE', 'Lore General'), ('EVENTO', 'Evento Histórico'), ('REGLA', 'Regla/Ley')], default='LORE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narrativas', to='persistence.caosworldorm')),
            ],
            options={
                'db_table': 'caos_narratives',
                'ordering': ['nid'],
            },
        ),
    ]
