# Generated by Django 5.0.1 on 2025-11-25 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaosVersionORM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_name', models.CharField(max_length=255)),
                ('proposed_description', models.TextField(blank=True, null=True)),
                ('version_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('change_log', models.CharField(blank=True, max_length=255)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='persistence.caosworldorm')),
            ],
            options={
                'db_table': 'caos_versions',
                'ordering': ['-version_number'],
            },
        ),
    ]
