# Generated by Django 5.0.1 on 2025-11-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0002_caosnarrativeorm'),
    ]

    operations = [
        migrations.AddField(
            model_name='caosnarrativeorm',
            name='menciones',
            field=models.ManyToManyField(blank=True, related_name='menciones_en_narrativa', to='persistence.caosworldorm'),
        ),
    ]
