# Generated by Django 5.0.1 on 2025-11-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0003_caosversionorm_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caosworldorm',
            name='current_author_name',
            field=models.CharField(blank=True, default='Sistema', max_length=150),
        ),
    ]
