# Generated by Django 5.0.1 on 2025-11-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0003_caosnarrativeorm_menciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caosnarrativeorm',
            name='tipo',
            field=models.CharField(choices=[('LORE', '📜 Lore / Enciclopedia'), ('HISTORIA', '📖 Historia / Novela'), ('CAPITULO', '📑 Capítulo'), ('EVENTO', '⚔️ Evento Histórico'), ('LEYENDA', '🕯️ Leyenda / Mito'), ('REGLA', '⚖️ Regla / Ley'), ('BESTIARIO', '🐉 Entrada de Bestiario')], default='LORE', max_length=20),
        ),
    ]
