# Generated by Django 5.0.1 on 2025-11-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0004_caosworldorm_current_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='caosversionorm',
            name='cambios',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='caosversionorm',
            name='es_version_activa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caosworldorm',
            name='eliminada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caosworldorm',
            name='id_codificado',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='caosworldorm',
            name='id_lore',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='caosworldorm',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='caosworldorm',
            name='visible_publico',
            field=models.BooleanField(default=False),
        ),
    ]
