# Generated by Django 5.0.1 on 2025-12-02 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0004_alter_caosnarrativeorm_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caosnarrativeorm',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='narrativas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caosnarrativeorm',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
