# Generated by Django 5.0.1 on 2025-11-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0005_caosversionorm_cambios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caosversionorm',
            name='proposed_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='caosversionorm',
            name='status',
            field=models.CharField(default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='caosworldorm',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
