# Generated by Django 5.0.1 on 2025-12-02 16:32

import src.Infrastructure.DjangoFramework.persistence.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0006_caosworldorm_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caosworldorm',
            name='public_id',
            field=models.CharField(default=src.Infrastructure.DjangoFramework.persistence.models.get_nanoid, editable=False, max_length=12, null=True, unique=True),
        ),
    ]
