# Generated by Django 5.0.1 on 2025-12-02 19:21

import django.db.models.deletion
import src.Infrastructure.DjangoFramework.persistence.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0007_alter_caosworldorm_public_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caosnarrativeorm',
            name='public_id',
            field=models.CharField(default=src.Infrastructure.DjangoFramework.persistence.models.generate_nanoid, editable=False, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='caosnarrativeorm',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='caosnarrativeorm',
            name='narrador',
            field=models.CharField(default='???', max_length=150),
        ),
        migrations.AlterField(
            model_name='caosnarrativeorm',
            name='tipo',
            field=models.CharField(choices=[('LORE', '📜 Lore'), ('HISTORIA', '📖 Historia'), ('CAPITULO', '📑 Capítulo'), ('EVENTO', '⚔️ Evento'), ('LEYENDA', '🕯️ Leyenda'), ('REGLA', '⚖️ Regla'), ('BESTIARIO', '🐉 Bestiario')], default='LORE', max_length=20),
        ),
        migrations.AlterField(
            model_name='caosworldorm',
            name='public_id',
            field=models.CharField(default=src.Infrastructure.DjangoFramework.persistence.models.generate_nanoid, editable=False, max_length=12, null=True),
        ),
    ]
