# Generated by Django 5.0.1 on 2025-12-02 19:22

import src.Infrastructure.DjangoFramework.persistence.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0008_caosnarrativeorm_public_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caosworldorm',
            name='public_id',
            field=models.CharField(default=src.Infrastructure.DjangoFramework.persistence.models.generate_nanoid, editable=False, max_length=12, unique=True),
        ),
    ]
