# Generated by Django 5.0.1 on 2025-12-02 21:45

import src.Infrastructure.DjangoFramework.persistence.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0010_alter_caosnarrativeorm_public_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caosepochorm',
            options={},
        ),
        migrations.AlterModelOptions(
            name='caosnarrativeorm',
            options={},
        ),
        migrations.AlterModelOptions(
            name='caosversionorm',
            options={},
        ),
        migrations.AlterField(
            model_name='caosnarrativeorm',
            name='public_id',
            field=models.CharField(default=src.Infrastructure.DjangoFramework.persistence.models.generate_nanoid, editable=False, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='caosnarrativeorm',
            name='tipo',
            field=models.CharField(default='LORE', max_length=20),
        ),
        migrations.AlterField(
            model_name='caosworldorm',
            name='public_id',
            field=models.CharField(default=src.Infrastructure.DjangoFramework.persistence.models.generate_nanoid, editable=False, max_length=12, null=True),
        ),
    ]
