# Generated by Django 5.2.9 on 2025-12-04 12:18

import django.db.models.deletion
import src.Infrastructure.DjangoFramework.persistence.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0011_alter_caosepochorm_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caosepochorm',
            options={'ordering': ['start_year']},
        ),
        migrations.AlterModelOptions(
            name='caosnarrativeorm',
            options={'ordering': ['nid']},
        ),
        migrations.AlterModelOptions(
            name='caosversionorm',
            options={'ordering': ['-version_number']},
        ),
        migrations.AlterField(
            model_name='caosnarrativeorm',
            name='public_id',
            field=models.CharField(default=src.Infrastructure.DjangoFramework.persistence.models.generate_nanoid, editable=False, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='caosnarrativeorm',
            name='tipo',
            field=models.CharField(choices=[('LORE', '📜 Lore'), ('HISTORIA', '📖 Historia'), ('CAPITULO', '📑 Capítulo'), ('EVENTO', '⚔️ Evento'), ('LEYENDA', '🕯️ Leyenda'), ('REGLA', '⚖️ Regla'), ('BESTIARIO', '🐉 Bestiario')], default='LORE', max_length=20),
        ),
        migrations.AlterField(
            model_name='caosworldorm',
            name='public_id',
            field=models.CharField(default=src.Infrastructure.DjangoFramework.persistence.models.generate_nanoid, editable=False, max_length=12, unique=True),
        ),
        migrations.CreateModel(
            name='CaosEventLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'caos_event_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
