# Generated by Django 5.2.9 on 2025-12-04 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0012_alter_caosepochorm_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caosnarrativeorm',
            name='current_version_number',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='CaosNarrativeVersionORM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_title', models.CharField(max_length=200)),
                ('proposed_content', models.TextField()),
                ('version_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='PENDING', max_length=30)),
                ('change_log', models.CharField(blank=True, max_length=255)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('narrative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='persistence.caosnarrativeorm')),
            ],
            options={
                'db_table': 'caos_narrative_versions',
                'ordering': ['-version_number'],
            },
        ),
    ]
