# Generated by Django 5.2.9 on 2025-12-04 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0013_caosnarrativeorm_current_version_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaosImageProposalORM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='temp_proposals/')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(default='PENDING', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_proposals', to='persistence.caosworldorm')),
            ],
            options={
                'db_table': 'caos_image_proposals',
                'ordering': ['-created_at'],
            },
        ),
    ]
