# Generated by Django 5.2.9 on 2025-12-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0014_caosimageproposalorm'),
    ]

    operations = [
        migrations.AddField(
            model_name='caosimageproposalorm',
            name='action',
            field=models.CharField(choices=[('ADD', 'Añadir'), ('DELETE', 'Borrar')], default='ADD', max_length=20),
        ),
        migrations.AddField(
            model_name='caosimageproposalorm',
            name='target_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='caosimageproposalorm',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='temp_proposals/'),
        ),
    ]
