# Generated by Django 5.2.9 on 2025-12-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0015_caosimageproposalorm_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caosnarrativeversionorm',
            name='action',
            field=models.CharField(choices=[('ADD', 'Crear'), ('EDIT', 'Editar'), ('DELETE', 'Borrar')], default='EDIT', max_length=20),
        ),
    ]
