# Generated by Django 5.2.9 on 2025-12-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0016_caosnarrativeversionorm_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=50, unique=True)),
                ('schema_definition', models.JSONField(default=dict)),
                ('ui_config', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'metadata_templates',
            },
        ),
    ]
