# Generated by Django 5.2.9 on 2025-12-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence", "0017_metadatatemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="caosworldorm",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="caosworldorm",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Si es False, está en la papelera."
            ),
        ),
    ]
