# Generated by Django 5.2.9 on 2025-12-17 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence", "0020_caosworldorm_author"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContributionProposal",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("proposed_payload", models.JSONField()),
                ("status", models.CharField(default="PENDING", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("contribution_type", models.CharField(default="EDIT", max_length=20)),
                (
                    "proposer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contributions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="persistence.caosworldorm",
                    ),
                ),
            ],
            options={
                "db_table": "contribution_proposals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rank",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("SUBADMIN", "Subadmin"),
                            ("USER", "User"),
                        ],
                        default="USER",
                        max_length=20,
                    ),
                ),
                (
                    "boss",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="minions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
