# Generated by Django 5.2.9 on 2025-12-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence", "0021_contributionproposal_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="boss",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="collaborators",
            field=models.ManyToManyField(
                blank=True, related_name="bosses", to="persistence.userprofile"
            ),
        ),
    ]
