# Generated by Django 5.2.9 on 2025-12-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence", "0022_remove_userprofile_boss_userprofile_collaborators"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="caosworldorm",
            name="id_codificado",
        ),
        migrations.AddField(
            model_name="caosimageproposalorm",
            name="reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="caosworldorm",
            name="allow_proposals",
            field=models.BooleanField(
                default=True, help_text="Si True, permite propuestas de terceros."
            ),
        ),
    ]
