# Generated by Django 5.2.9 on 2025-12-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence", "0023_remove_caosworldorm_id_codificado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="caosimageproposalorm",
            name="admin_feedback",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="caosnarrativeversionorm",
            name="admin_feedback",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="caosversionorm",
            name="admin_feedback",
            field=models.TextField(blank=True),
        ),
    ]
