# Generated by Django 5.2.9 on 2025-12-28 16:19

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence", "0026_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChronicleEventORM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        default=0, help_text="Año del evento en la cronología universal"
                    ),
                ),
                (
                    "data_changes",
                    models.JSONField(
                        default=dict, help_text="Delta de metadatos o snapshot parcial"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("FOUNDATION", "Fundación"),
                            ("CATACLYSM", "Cataclismo"),
                            ("EVOLUTION", "Evolución Natural"),
                            ("POLITICAL", "Cambio Político"),
                            ("MANUAL", "Ajuste Manual"),
                        ],
                        default="MANUAL",
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Orden de aplicación para eventos del mismo año (Mayor = Después)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chronicle_events",
                        to="persistence.caosworldorm",
                    ),
                ),
            ],
            options={
                "db_table": "caos_chronicle_events",
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["data_changes"], name="idx_chronicle_data_gin"
                    ),
                    models.Index(
                        fields=["entity", "year", "priority"], name="idx_chronicle_timeline"
                    ),
                ],
            },
        ),
    ]
