# Generated by Django 5.2.9 on 2025-12-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence", "0027_chronicleeventorm"),
    ]

    operations = [
        migrations.AddField(
            model_name="chronicleeventorm",
            name="narrative_summary",
            field=models.TextField(
                blank=True,
                help_text="Explicación narrativa del cambio (Human/AI Readable)",
                null=True,
            ),
        ),
    ]
