# Generated by Django 5.2.9 on 2025-12-29 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("persistence", "0031_extend_version_for_timeline"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChronicleEventORM",
        ),
    ]
