# Generated by Django 5.0.1 on 2025-12-29 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence", "0032_delete_chronicleeventorm"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimelinePeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text='Título del período: "Inicios", "Expansión", etc.', max_length=100
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text='URL-friendly: "inicios", "expansion"', max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Descripción/Lore del período"),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Orden de visualización (menor = primero)"
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=False, help_text="True si es el estado ACTUAL/presente"
                    ),
                ),
                (
                    "cover_image",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del archivo de portada",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "world",
                    models.ForeignKey(
                        help_text="Entidad a la que pertenece este período",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_periods",
                        to="persistence.caosworldorm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Período Temporal",
                "verbose_name_plural": "Períodos Temporales",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="TimelinePeriodVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "version_number",
                    models.IntegerField(help_text="Número de versión (V1, V2, V3...)"),
                ),
                (
                    "proposed_title",
                    models.CharField(
                        blank=True, help_text="Nuevo título propuesto (si cambia)", max_length=100
                    ),
                ),
                (
                    "proposed_description",
                    models.TextField(blank=True, help_text="Nueva descripción propuesta"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("APPROVED", "Aprobada"),
                            ("REJECTED", "Rechazada"),
                            ("ARCHIVED", "Archivada"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "change_log",
                    models.TextField(blank=True, help_text="Descripción de los cambios"),
                ),
                (
                    "admin_feedback",
                    models.TextField(blank=True, help_text="Feedback del admin (si rechazada)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Autor de la propuesta",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timeline_period_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        help_text="Período al que pertenece esta versión",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="persistence.timelineperiod",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin que revisó",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_timeline_period_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Versión de Período",
                "verbose_name_plural": "Versiones de Períodos",
                "ordering": ["-version_number"],
            },
        ),
        migrations.AddIndex(
            model_name="timelineperiod",
            index=models.Index(
                fields=["world", "is_current"], name="persistence_world_i_8ee372_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timelineperiod",
            index=models.Index(fields=["world", "slug"], name="persistence_world_i_d5aad0_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="timelineperiod",
            unique_together={("world", "slug")},
        ),
        migrations.AlterUniqueTogether(
            name="timelineperiodversion",
            unique_together={("period", "version_number")},
        ),
    ]
