# Generated by Django 5.0.1 on 2025-12-29 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence", "0033_create_timeline_period_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="caosimageproposalorm",
            name="timeline_period",
            field=models.ForeignKey(
                blank=True,
                help_text="Período al que pertenece esta imagen (nulo = ACTUAL)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="images",
                to="persistence.timelineperiod",
            ),
        ),
        migrations.AddField(
            model_name="caosnarrativeorm",
            name="timeline_period",
            field=models.ForeignKey(
                blank=True,
                help_text="Período al que pertenece esta narrativa (nulo = ACTUAL)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="narratives",
                to="persistence.timelineperiod",
            ),
        ),
    ]
