# Generated by Django 5.0.1 on 2025-12-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence", "0034_add_period_to_media_narrative"),
    ]

    operations = [
        migrations.AddField(
            model_name="timelineperiod",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Metadatos adicionales del periodo (clima, población, etc)",
            ),
        ),
        migrations.AddField(
            model_name="timelineperiodversion",
            name="action",
            field=models.CharField(
                choices=[("ADD", "Añadir"), ("EDIT", "Editar"), ("DELETE", "Eliminar")],
                default="EDIT",
                help_text="Tipo de acción propuesta",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="timelineperiodversion",
            name="proposed_metadata",
            field=models.JSONField(
                blank=True, default=dict, help_text="Nuevos metadatos propuestos"
            ),
        ),
    ]
