# Generated by Django 5.2.9 on 2025-12-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence", "0035_timelineperiod_metadata_timelineperiodversion_action_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timelineperiod",
            name="slug",
            field=models.SlugField(
                help_text='URL-friendly: "inicios", "expansion"', max_length=150
            ),
        ),
    ]
