# Generated by Django 5.0.1 on 2025-12-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence", "0036_extend_period_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="timelineperiod",
            name="is_future",
            field=models.BooleanField(
                default=False, help_text="True si es un borrador futuro (Offline)"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="rank",
            field=models.CharField(
                choices=[("ADMIN", "Admin"), ("SUBADMIN", "Subadmin"), ("EXPLORER", "Explorador")],
                default="EXPLORER",
                max_length=20,
            ),
        ),
    ]
