# Generated by Django 5.2.9 on 2025-12-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence", "0039_caoscomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
