# Generated by Django 5.2.9 on 2025-12-30 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence", "0040_userprofile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="caoscomment",
            name="parent_comment",
            field=models.ForeignKey(
                blank=True,
                help_text="Comentario padre si es una respuesta",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="persistence.caoscomment",
            ),
        ),
        migrations.AddField(
            model_name="caoscomment",
            name="reply_count",
            field=models.IntegerField(default=0, help_text="Número de respuestas"),
        ),
    ]
