# Generated by Django 5.2.9 on 2026-01-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence", "0042_caosnotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="caoscomment",
            name="entity_name",
            field=models.CharField(
                blank=True,
                help_text="Nombre legible de la entidad (ej: 'Mundo: Caos Prime')",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="caoscomment",
            name="entity_type",
            field=models.CharField(
                blank=True, help_text="Tipo de entidad (NARRATIVE, IMAGE, WORLD)", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="caoscomment",
            name="status",
            field=models.CharField(
                choices=[("NEW", "Nuevo"), ("REPLIED", "Respondido"), ("ARCHIVED", "Archivado")],
                default="NEW",
                max_length=10,
            ),
        ),
    ]
