# Generated by Django 5.2.9 on 2026-01-03 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence", "0043_caoscomment_entity_name_caoscomment_entity_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="caoscomment",
            name="rating",
            field=models.IntegerField(
                blank=True, help_text="Puntuación (1-5 estrellas)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="caoscomment",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "Nuevo"),
                    ("REPLIED", "Respondido"),
                    ("ARCHIVED", "Archivado"),
                    ("DELETED", "Eliminado"),
                ],
                default="NEW",
                max_length=10,
            ),
        ),
    ]
